sudo: required

language: ruby

services:
  - docker

cache:
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker pull tolsi/ledger-devenv

script:
  - docker run -t -v `pwd`:/home/app -i tolsi/ledger-devenv /bin/bash -c "cd /home && git clone --branch nanos-1421 https://github.com/LedgerHQ/nanos-secure-sdk.git && git clone --branch blue-r23 https://github.com/LedgerHQ/blue-secure-sdk.git && cd app && make BOLOS_ENV=/opt/ledger-blue/ BOLOS_SDK=/home/nanos-secure-sdk && if [[ "$(grep '0x300 00' debug/app.map | awk '{print $2}')" > "0x20002100" ]] then exit -1 fi"